version: "3.8"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"

  mongo:
    image: mongodb/mongodb-atlas-local:8
    container_name: mongodb-8
    environment:
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
